name: Upload
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Server 🚀
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
      - name: Upload to server
        uses: Creepios/sftp-action@v1.0.3
        with:
          host: zedruc.net
          username: markus
          port: 22
          password: ${{ secrets.ftp_password }}
          localPath: ./public/
          remotePath: /home/markus/servers/zedruc_net/website/atc24-suite/
